service: import-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ca-central-1
  environment:
    SQS_QUEUE_URL: https://sqs.ca-central-1.amazonaws.com/038887531393/products-dev-CatalogItemsQueue-C8YJJbMHBiqW
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
        - s3:CopyObject
        - sqs:SendMessage
      Resource:
        - arn:aws:s3:::upload-aws-js/uploaded/*
        - arn:aws:s3:::upload-aws-js/parsed/*
        - arn:aws:sqs:ca-central-1:038887531393:products-dev-CatalogItemsQueue-C8YJJbMHBiqW

functions:
  importProductsFile:
    handler: functions/import-products-file.handler
    events:
      - http:
          path: import
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer:
            type: TOKEN
            name: basicAuthorizer
            identitySource: method.request.header.Authorization
            arn: arn:aws:lambda:ca-central-1:038887531393:function:authorization-service-dev-basicAuthorizer
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: functions/import-file-parser.handler
    events:
      - s3:
          bucket: upload-aws-js
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true